services:
  db:
    image: postgres:14.13
    hostname: postgres
    restart: 'always'
    volumes:
      - pgdata14:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  web:
    image: resource-locker:latest
    command:
      - /bin/sh
      - -c
      - bundle exec rackup config.ru -p 3000
    volumes:
      - .:/resource-locker
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://test@db:5432
volumes:
  pgdata14:
