# database.yml

production:
  adapter: postgresql
  encoding: unicode
  database: resource_lock_production
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: resource_lock_dev
  pool: 5

test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500
